version: '3.8'

services:
  db:
    image: postgres:15
    container_name: evcharges_db
    restart: always
    environment:
      POSTGRES_DB: evcharges
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: evcharges_backend
    restart: always
    command: sh -c "python manage.py collectstatic --noinput &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    daphne -b 0.0.0.0 -p 8000 ElectricalVehicleCharges.asgi:application"
    volumes:
      - .:/ElectricalVehicleCharges
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/evcharges
      - DEBUG=True

  fastapi:
    build: .
    container_name: evcharges_fastapi
    restart: always
    command: uvicorn api.views:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - .:/ElectricalVehicleCharges
    ports:
      - "9000:9000"
    depends_on:
      - db
      - web
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/evcharges
      - DEBUG=True

volumes:
  postgres_data:
